# Generated by Django 5.1.8 on 2025-04-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripparticipant",
            name="role",
        ),
    ]
