# Generated by Django 5.1.8 on 2025-04-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_trip_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripinvitation",
            name="invited_by",
        ),
        migrations.RemoveField(
            model_name="tripinvitation",
            name="trip",
        ),
        migrations.RemoveField(
            model_name="tripitinerary",
            name="trip",
        ),
        migrations.AlterUniqueTogether(
            name="tripjoinrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="tripjoinrequest",
            name="trip",
        ),
        migrations.RemoveField(
            model_name="tripjoinrequest",
            name="user",
        ),
        migrations.DeleteModel(
            name="TripActivity",
        ),
        migrations.DeleteModel(
            name="TripInvitation",
        ),
        migrations.DeleteModel(
            name="TripItinerary",
        ),
        migrations.DeleteModel(
            name="TripJoinRequest",
        ),
    ]
