# Generated by Django 5.1.8 on 2025-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="trip_visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="public",
                max_length=10,
            ),
        ),
    ]
